version: "3.9"

services:
  budget-app-backend:
    container_name: budget-app-backend
    image: budget-app-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: "3000"
      CORS_ORIGINS: '["http://localhost:5173", "http://localhost"]'
      CORS_MAX_AGE: 10800
      DATABASE_URL: "mysql://407528mp:cwNYscHqIIPYC99uiBgBlzBCfh3wZt8E@vichogent.be:41260/407528mp"
      AUTH_JWT_SECRET: "eensuperveiligsecretvoorindevelopment"
      AUTH_JWT_AUDIENCE: "budget.hogent.be"
      AUTH_JWT_ISSUER: "budget.hogent.be"
      AUTH_HASH_LENGTH: "32"
      AUTH_HASH_TIME_COST: "6"
      AUTH_HASH_MEMORY_COST: "65536"
      AUTH_MAX_DELAY: "2000"
      LOG_DISABLED: "false"
    ports:
      - "3000:3000"
